import { bigint, boolean, jsonb, pgTable, real, text, timestamp, unique, uuid, integer } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), role: text('role').notNull().default('member'), approved: boolean('approved').notNull().default(false), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }) })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull().references(() => user.id, { onDelete: 'cascade' }), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const nodes = pgTable('nodes', { id: uuid('id').primaryKey().defaultRandom(), userId: text('userId').notNull(), name: text('name').notNull(), agentTokenHash: text('agentTokenHash').notNull().unique(), status: text('status').notNull().default('offline'), lastHeartbeat: timestamp('lastHeartbeat'), cpuPercent: real('cpuPercent').notNull().default(0), memoryUsedMb: integer('memoryUsedMb').notNull().default(0), memoryTotalMb: integer('memoryTotalMb').notNull().default(0), diskUsedGb: real('diskUsedGb').notNull().default(0), diskTotalGb: real('diskTotalGb').notNull().default(0), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const servers = pgTable('servers', { id: uuid('id').primaryKey().defaultRandom(), userId: text('userId').notNull(), nodeId: uuid('nodeId').notNull(), name: text('name').notNull(), loader: text('loader').notNull(), mcVersion: text('mcVersion').notNull(), loaderVersion: text('loaderVersion'), memoryMb: integer('memoryMb').notNull().default(4096), port: integer('port').notNull().default(25565), status: text('status').notNull().default('stopped'), installProgress: integer('installProgress').notNull().default(0), installError: text('installError'), playerCount: integer('playerCount').notNull().default(0), pid: integer('pid'), worldName: text('worldName').notNull().default('world'), itemTrackingEnabled: boolean('itemTrackingEnabled').notNull().default(false), javaArgs: text('javaArgs').notNull().default(''), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const worlds = pgTable('worlds', { id: uuid('id').primaryKey().defaultRandom(), userId: text('userId').notNull(), serverId: uuid('serverId').notNull(), name: text('name').notNull(), seed: text('seed'), isActive: boolean('isActive').notNull().default(false), sizeMb: real('sizeMb').notNull().default(0), lastBackupAt: timestamp('lastBackupAt'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const mods = pgTable('mods', { id: uuid('id').primaryKey().defaultRandom(), userId: text('userId').notNull(), serverId: uuid('serverId').notNull(), filename: text('filename').notNull(), blobPathname: text('blobPathname').notNull(), sha256: text('sha256').notNull(), enabled: boolean('enabled').notNull().default(true), uploadedBy: text('uploadedBy').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const backups = pgTable('backups', { id: uuid('id').primaryKey().defaultRandom(), userId: text('userId').notNull(), worldId: uuid('worldId').notNull(), blobPathname: text('blobPathname').notNull(), sizeMb: real('sizeMb').notNull().default(0), sizeBytes: bigint('sizeBytes', { mode: 'number' }).notNull().default(0), createdBy: text('createdBy').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const serverPermissions = pgTable('server_permissions', { id: uuid('id').primaryKey().defaultRandom(), userId: text('userId').notNull(), ownerUserId: text('ownerUserId').notNull(), serverId: uuid('serverId').notNull(), canStart: boolean('canStart').notNull().default(false), canStop: boolean('canStop').notNull().default(false), canRestart: boolean('canRestart').notNull().default(false), canConsole: boolean('canConsole').notNull().default(false), canFiles: boolean('canFiles').notNull().default(false), canBackup: boolean('canBackup').notNull().default(false), canReset: boolean('canReset').notNull().default(false), canViewLostItems: boolean('canViewLostItems').notNull().default(false), canManageLostItems: boolean('canManageLostItems').notNull().default(false), createdAt: timestamp('createdAt').notNull().defaultNow() }, (t) => [unique().on(t.userId, t.serverId)])
export const auditLog = pgTable('audit_log', { id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(), userId: text('userId').notNull(), action: text('action').notNull(), resourceType: text('resourceType').notNull(), resourceId: text('resourceId'), details: jsonb('details').notNull().default({}), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const agentCommands = pgTable('agent_commands', { id: uuid('id').primaryKey().defaultRandom(), userId: text('userId').notNull(), nodeId: uuid('nodeId').notNull(), serverId: uuid('serverId'), type: text('type').notNull(), payload: jsonb('payload').notNull().default({}), status: text('status').notNull().default('queued'), result: jsonb('result'), createdAt: timestamp('createdAt').notNull().defaultNow(), completedAt: timestamp('completedAt') })
export const consoleLogs = pgTable('console_logs', { id: bigint('id', { mode: 'number' }).primaryKey().generatedAlwaysAsIdentity(), userId: text('userId').notNull(), serverId: uuid('serverId').notNull(), stream: text('stream').notNull().default('stdout'), line: text('line').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export { lostItems, operationLogs } from './lost-items-schema'
