export type WorldNativeProfile = { gamemode:'survival'|'creative'|'adventure'; difficulty:'peaceful'|'easy'|'normal'|'hard'; hardcore:boolean; levelType:'default'|'flat'|'largeBiomes'|'amplified'; generateStructures:boolean }
export type WorldTemplate = { id:string; name:string; category:string; mode:'native'|'package'; description:string; profile?:WorldNativeProfile; packageKey?:string }

const rows:[string,string,string][] = [
  ["Survival ve Hardcore","Klasik Survival","klasik-survival"],
  ["Survival ve Hardcore","Hardcore Survival","hardcore-survival"],
  ["Survival ve Hardcore","Ultra Hardcore","ultra-hardcore"],
  ["Survival ve Hardcore","Tek Can Survival","tek-can-survival"],
  ["Survival ve Hardcore","Yarım Kalp Challenge","yarim-kalp-challenge"],
  ["Survival ve Hardcore","Can Yenilenmeyen Survival","can-yenilenmeyen-survival"],
  ["Survival ve Hardcore","Zırhsız Survival","zirhsiz-survival"],
  ["Survival ve Hardcore","Silahsız Survival","silahsiz-survival"],
  ["Survival ve Hardcore","Yataksız Survival","yataksiz-survival"],
  ["Survival ve Hardcore","Koordinatsız Survival","koordinatsiz-survival"],
  ["Survival ve Hardcore","Craft Yapmadan Survival","craft-yapmadan-survival"],
  ["Survival ve Hardcore","Maden Kazmadan Survival","maden-kazmadan-survival"],
  ["Survival ve Hardcore","Köylü Kullanmadan Survival","koylu-kullanmadan-survival"],
  ["Survival ve Hardcore","Vegan Survival","vegan-survival"],
  ["Survival ve Hardcore","Barışçıl Survival","bariscil-survival"],
  ["SkyBlock ve Void","Klasik SkyBlock","klasik-skyblock"],
  ["SkyBlock ve Void","Hardcore SkyBlock","hardcore-skyblock"],
  ["SkyBlock ve Void","Extreme SkyBlock","extreme-skyblock"],
  ["SkyBlock ve Void","Lucky Block SkyBlock","lucky-block-skyblock"],
  ["SkyBlock ve Void","One Chunk SkyBlock","one-chunk-skyblock"],
  ["SkyBlock ve Void","Void SkyBlock","void-skyblock"],
  ["SkyBlock ve Void","Nether SkyBlock","nether-skyblock"],
  ["SkyBlock ve Void","End SkyBlock","end-skyblock"],
  ["SkyBlock ve Void","Biome SkyBlock","biome-skyblock"],
  ["SkyBlock ve Void","RPG SkyBlock","rpg-skyblock"],
  ["SkyBlock ve Void","Economy SkyBlock","economy-skyblock"],
  ["SkyBlock ve Void","Multiplayer SkyBlock","multiplayer-skyblock"],
  ["SkyBlock ve Void","Random Item SkyBlock","random-item-skyblock"],
  ["SkyBlock ve Void","Boss SkyBlock","boss-skyblock"],
  ["SkyBlock ve Void","Ada Genişleten SkyBlock","ada-genisleten-skyblock"],
  ["OneBlock","Klasik OneBlock","klasik-oneblock"],
  ["OneBlock","Hardcore OneBlock","hardcore-oneblock"],
  ["OneBlock","Random OneBlock","random-oneblock"],
  ["OneBlock","Lucky OneBlock","lucky-oneblock"],
  ["OneBlock","OneBlock RPG","oneblock-rpg"],
  ["OneBlock","OneBlock Boss Rush","oneblock-boss-rush"],
  ["OneBlock","OneBlock Multiplayer","oneblock-multiplayer"],
  ["OneBlock","OneBlock 100 Gün","oneblock-100-gun"],
  ["OneBlock","OneBlock Nether","oneblock-nether"],
  ["OneBlock","OneBlock End","oneblock-end"],
  ["Küçük Dünya Challenge","One Chunk Survival","one-chunk-survival"],
  ["Küçük Dünya Challenge","100x100 Dünya","100x100-dunya"],
  ["Küçük Dünya Challenge","50x50 Dünya","50x50-dunya"],
  ["Küçük Dünya Challenge","25x25 Dünya","25x25-dunya"],
  ["Küçük Dünya Challenge","10x10 Dünya","10x10-dunya"],
  ["Küçük Dünya Challenge","5x5 Dünya","5x5-dunya"],
  ["Küçük Dünya Challenge","Dünya Sınırı Her Gün Büyüyor","dunya-siniri-her-gun-buyuyor"],
  ["Küçük Dünya Challenge","Dünya Sınırı Her Gün Küçülüyor","dunya-siniri-her-gun-kuculuyor"],
  ["Küçük Dünya Challenge","Tek Ada Survival","tek-ada-survival"],
  ["Küçük Dünya Challenge","Tek Biyom Survival","tek-biyom-survival"],
  ["Tek Biyom Dünyaları","Sadece Çöl","sadece-col"],
  ["Tek Biyom Dünyaları","Sadece Kar","sadece-kar"],
  ["Tek Biyom Dünyaları","Sadece Orman","sadece-orman"],
  ["Tek Biyom Dünyaları","Sadece Jungle","sadece-jungle"],
  ["Tek Biyom Dünyaları","Sadece Savanna","sadece-savanna"],
  ["Tek Biyom Dünyaları","Sadece Okyanus","sadece-okyanus"],
  ["Tek Biyom Dünyaları","Sadece Dağ","sadece-dag"],
  ["Tek Biyom Dünyaları","Sadece Bataklık","sadece-bataklik"],
  ["Tek Biyom Dünyaları","Sadece Mushroom Island","sadece-mushroom-island"],
  ["Tek Biyom Dünyaları","Sadece Deep Dark","sadece-deep-dark"],
  ["Boyut Challenge","Nether Only Survival","nether-only-survival"],
  ["Boyut Challenge","End Only Survival","end-only-survival"],
  ["Boyut Challenge","Overworld Yasak","overworld-yasak"],
  ["Boyut Challenge","Nether’da 100 Gün","nether-da-100-gun"],
  ["Boyut Challenge","End’de 100 Gün","end-de-100-gun"],
  ["Boyut Challenge","Ancient City Survival","ancient-city-survival"],
  ["Boyut Challenge","Yeraltı Survival","yeralti-survival"],
  ["Boyut Challenge","Mağaradan Çıkmadan Survival","magaradan-cikmadan-survival"],
  ["Boyut Challenge","Bedrock Seviyesinde Survival","bedrock-seviyesinde-survival"],
  ["Boyut Challenge","Gökyüzünde Survival","gokyuzunde-survival"],
  ["Rastgele Minecraft","Random Block Drops","random-block-drops"],
  ["Rastgele Minecraft","Random Mob Drops","random-mob-drops"],
  ["Rastgele Minecraft","Random Crafting Recipes","random-crafting-recipes"],
  ["Rastgele Minecraft","Random Loot","random-loot"],
  ["Rastgele Minecraft","Random Enchantments","random-enchantments"],
  ["Rastgele Minecraft","Random Effects Every Minute","random-effects-every-minute"],
  ["Rastgele Minecraft","Random Item Every Minute","random-item-every-minute"],
  ["Rastgele Minecraft","Random Mob Every Minute","random-mob-every-minute"],
  ["Rastgele Minecraft","Random Biome World","random-biome-world"],
  ["Rastgele Minecraft","Random Structure World","random-structure-world"],
  ["Dünya Felaketleri","Lava Rising","lava-rising"],
  ["Dünya Felaketleri","Water Rising","water-rising"],
  ["Dünya Felaketleri","Void Rising","void-rising"],
  ["Dünya Felaketleri","Sand Rising","sand-rising"],
  ["Dünya Felaketleri","Dünya Her Dakika Yok Oluyor","dunya-her-dakika-yok-oluyor"],
  ["Dünya Felaketleri","Dünya TNT’den Oluşuyor","dunya-tnt-den-olusuyor"],
  ["Dünya Felaketleri","Meteor Yağmuru Survival","meteor-yagmuru-survival"],
  ["Dünya Felaketleri","Volkan Survival","volkan-survival"],
  ["Dünya Felaketleri","Sonsuz Fırtına","sonsuz-firtina"],
  ["Dünya Felaketleri","Sonsuz Gece","sonsuz-gece"],
  ["Kıyamet","Zombie Apocalypse","zombie-apocalypse"],
  ["Kıyamet","Mutant Apocalypse","mutant-apocalypse"],
  ["Kıyamet","Parasite Apocalypse","parasite-apocalypse"],
  ["Kıyamet","Alien Invasion","alien-invasion"],
  ["Kıyamet","Nuclear Apocalypse","nuclear-apocalypse"],
  ["Kıyamet","Wither Apocalypse","wither-apocalypse"],
  ["Kıyamet","Warden Apocalypse","warden-apocalypse"],
  ["Kıyamet","Skeleton Apocalypse","skeleton-apocalypse"],
  ["Kıyamet","Creeper Apocalypse","creeper-apocalypse"],
  ["Kıyamet","Enderman Apocalypse","enderman-apocalypse"],
  ["100 Gün Serileri","Hardcore’da 100 Gün","hardcore-da-100-gun"],
  ["100 Gün Serileri","SkyBlock’ta 100 Gün","skyblock-ta-100-gun"],
  ["100 Gün Serileri","OneBlock’ta 100 Gün","oneblock-ta-100-gun"],
  ["100 Gün Serileri","Çölde 100 Gün","colde-100-gun"],
  ["100 Gün Serileri","Buz Dünyasında 100 Gün","buz-dunyasinda-100-gun"],
  ["100 Gün Serileri","Okyanusta 100 Gün","okyanusta-100-gun"],
  ["100 Gün Serileri","Yeraltında 100 Gün","yeraltinda-100-gun"],
  ["100 Gün Serileri","Zombie Kıyametinde 100 Gün","zombie-kiyametinde-100-gun"],
  ["100 Gün Serileri","Tek Chunk’ta 100 Gün","tek-chunk-ta-100-gun"],
  ["100 Gün Serileri","Orta Çağ Dünyasında 100 Gün","orta-cag-dunyasinda-100-gun"],
  ["RPG ve Fantastik","Medieval RPG","medieval-rpg"],
  ["RPG ve Fantastik","Dark Fantasy RPG","dark-fantasy-rpg"],
  ["RPG ve Fantastik","Magic Survival","magic-survival"],
  ["RPG ve Fantastik","Wizard World","wizard-world"],
  ["RPG ve Fantastik","Dragon Survival","dragon-survival"],
  ["RPG ve Fantastik","Dungeons RPG","dungeons-rpg"],
  ["RPG ve Fantastik","Boss Progression World","boss-progression-world"],
  ["RPG ve Fantastik","Level Sistemi Survival","level-sistemi-survival"],
  ["RPG ve Fantastik","Skill Tree Survival","skill-tree-survival"],
  ["RPG ve Fantastik","Quest Survival","quest-survival"],
  ["Krallık ve Medeniyet","Kingdom Survival","kingdom-survival"],
  ["Krallık ve Medeniyet","Medieval Kingdom","medieval-kingdom"],
  ["Krallık ve Medeniyet","Civilization World","civilization-world"],
  ["Krallık ve Medeniyet","Nations SMP","nations-smp"],
  ["Krallık ve Medeniyet","Empire SMP","empire-smp"],
  ["Krallık ve Medeniyet","Towny Survival","towny-survival"],
  ["Krallık ve Medeniyet","Kabile Survival","kabile-survival"],
  ["Krallık ve Medeniyet","Kingdom Wars","kingdom-wars"],
  ["Krallık ve Medeniyet","Viking Survival","viking-survival"],
  ["Krallık ve Medeniyet","Samurai Survival","samurai-survival"],
  ["Korku","Herobrine Survival","herobrine-survival"],
  ["Korku","From The Fog Survival","from-the-fog-survival"],
  ["Korku","Cave Horror","cave-horror"],
  ["Korku","Backrooms Minecraft","backrooms-minecraft"],
  ["Korku","SCP Survival","scp-survival"],
  ["Korku","Haunted Forest","haunted-forest"],
  ["Korku","Terk Edilmiş Şehir","terk-edilmis-sehir"],
  ["Korku","Sisli Dünya Survival","sisli-dunya-survival"],
  ["Korku","Gece Canavarı Survival","gece-canavari-survival"],
  ["Korku","Wendigo Survival","wendigo-survival"],
  ["Eğlencelik ve Rekabetçi","Minecraft Manhunt","minecraft-manhunt"],
  ["Eğlencelik ve Rekabetçi","Death Swap","death-swap"],
  ["Eğlencelik ve Rekabetçi","Block Shuffle","block-shuffle"],
  ["Eğlencelik ve Rekabetçi","Minecraft Bingo","minecraft-bingo"],
  ["Eğlencelik ve Rekabetçi","Lucky Block Race","lucky-block-race"],
  ["Eğlencelik ve Rekabetçi","Survival Island","survival-island"],
  ["Eğlencelik ve Rekabetçi","Raft Survival","raft-survival"],
  ["Eğlencelik ve Rekabetçi","Lifesteal SMP","lifesteal-smp"],
  ["Eğlencelik ve Rekabetçi","Anarchy Survival","anarchy-survival"],
  ["Eğlencelik ve Rekabetçi","100 Oyunculu Civilization","100-oyunculu-civilization"],
  ["Klasik Dünyalar","Survival","survival"],
  ["Klasik Dünyalar","Hardcore","hardcore"],
  ["Klasik Dünyalar","Creative","creative"],
  ["Klasik Dünyalar","Adventure","adventure"],
  ["Klasik Dünyalar","Peaceful Survival","peaceful-survival"],
  ["Klasik Dünyalar","Superflat Survival","superflat-survival"],
  ["Klasik Dünyalar","Amplified World","amplified-world"],
  ["Klasik Dünyalar","Large Biomes","large-biomes"],
  ["Klasik Dünyalar","Single Biome","single-biome"],
  ["Klasik Dünyalar","Only Desert","only-desert"],
  ["Klasik Dünyalar","Only Snow","only-snow"],
  ["Klasik Dünyalar","Only Jungle","only-jungle"],
  ["Klasik Dünyalar","Only Ocean","only-ocean"],
  ["Klasik Dünyalar","Only Mountains","only-mountains"],
  ["Klasik Dünyalar","Cave World","cave-world"],
  ["Klasik Dünyalar","Floating Islands","floating-islands"],
  ["Klasik Dünyalar","Nether Survival","nether-survival"],
  ["Klasik Dünyalar","End Survival","end-survival"],
  ["OneBlock Genişletilmiş","OneBlock SkyBlock","oneblock-skyblock"],
  ["OneBlock Genişletilmiş","OneBlock but Every Block Is Random","oneblock-but-every-block-is-random"],
  ["OneBlock Genişletilmiş","OneBlock With Bosses","oneblock-with-bosses"],
  ["OneBlock Genişletilmiş","OneBlock 100 Days","oneblock-100-days"],
  ["Kısıtlamalı Survival","One Biome Survival","one-biome-survival"],
  ["Kısıtlamalı Survival","One Island Survival","one-island-survival"],
  ["Kısıtlamalı Survival","One Cave Survival","one-cave-survival"],
  ["Kısıtlamalı Survival","Border Survival","border-survival"],
  ["Kısıtlamalı Survival","100x100 World","100x100-world"],
  ["Kısıtlamalı Survival","50x50 World","50x50-world"],
  ["Kısıtlamalı Survival","10x10 World","10x10-world"],
  ["Kısıtlamalı Survival","World Border Expands Every Day","world-border-expands-every-day"],
  ["Kısıtlamalı Survival","No Mining Challenge","no-mining-challenge"],
  ["Kısıtlamalı Survival","No Crafting Challenge","no-crafting-challenge"],
  ["Kısıtlamalı Survival","No Armor Challenge","no-armor-challenge"],
  ["Kısıtlamalı Survival","No Weapons Challenge","no-weapons-challenge"],
  ["Kısıtlamalı Survival","No Sleeping Challenge","no-sleeping-challenge"],
  ["Kısıtlamalı Survival","No Food Challenge","no-food-challenge"],
  ["Kısıtlamalı Survival","Pacifist Survival","pacifist-survival"],
  ["Kısıtlamalı Survival","No Coordinates Survival","no-coordinates-survival"],
  ["Kısıtlamalı Survival","Inventory Limited Survival","inventory-limited-survival"],
  ["Rastgele Dünyalar","Random Structures","random-structures"],
  ["Rastgele Dünyalar","Random Biomes","random-biomes"],
  ["Rastgele Dünyalar","Random Items Every Minute","random-items-every-minute"],
  ["Rastgele Dünyalar","Random Dimensions","random-dimensions"],
  ["Zorluk Dünyaları","Ultra Hardcore/UHC","ultra-hardcore-uhc"],
  ["Zorluk Dünyaları","Half-Heart Hardcore","half-heart-hardcore"],
  ["Zorluk Dünyaları","One Heart Survival","one-heart-survival"],
  ["Zorluk Dünyaları","No Regeneration","no-regeneration"],
  ["Zorluk Dünyaları","Permanent Night","permanent-night"],
  ["Zorluk Dünyaları","Permanent Day","permanent-day"],
  ["Zorluk Dünyaları","Eternal Winter","eternal-winter"],
  ["Zorluk Dünyaları","Eternal Rain","eternal-rain"],
  ["Zorluk Dünyaları","World Slowly Disappears","world-slowly-disappears"],
  ["Zorluk Dünyaları","Every Minute Border Shrinks","every-minute-border-shrinks"],
  ["Zorluk Dünyaları","Mobs Get Stronger Every Day","mobs-get-stronger-every-day"],
  ["Zorluk Dünyaları","Every Night Gets Harder","every-night-gets-harder"],
  ["Zorluk Dünyaları","Blood Moon Survival","blood-moon-survival"],
  ["100 Gün Konseptleri","100 Days Hardcore","100-days-hardcore"],
  ["100 Gün Konseptleri","100 Days SkyBlock","100-days-skyblock"],
  ["100 Gün Konseptleri","100 Days OneBlock","100-days-oneblock"],
  ["100 Gün Konseptleri","100 Days Zombie Apocalypse","100-days-zombie-apocalypse"],
  ["100 Gün Konseptleri","100 Days Desert","100-days-desert"],
  ["100 Gün Konseptleri","100 Days Frozen World","100-days-frozen-world"],
  ["100 Gün Konseptleri","100 Days Underground","100-days-underground"],
  ["100 Gün Konseptleri","100 Days Ocean Only","100-days-ocean-only"],
  ["100 Gün Konseptleri","100 Days Nether","100-days-nether"],
  ["100 Gün Konseptleri","100 Days End","100-days-end"],
  ["100 Gün Konseptleri","100 Days One Chunk","100-days-one-chunk"],
  ["100 Gün Konseptleri","100 Days With Dinosaurs","100-days-with-dinosaurs"],
  ["100 Gün Konseptleri","100 Days Medieval","100-days-medieval"],
  ["Kıyamet Temaları","Ice Age","ice-age"],
  ["Kıyamet Temaları","Global Flood","global-flood"],
  ["Kıyamet Temaları","Meteor Apocalypse","meteor-apocalypse"],
  ["Kıyamet Temaları","Volcano Apocalypse","volcano-apocalypse"],
  ["Kıyamet Temaları","Endless Night Apocalypse","endless-night-apocalypse"],
  ["Korku Dünyaları","Backrooms","backrooms"],
  ["Korku Dünyaları","Abandoned City","abandoned-city"],
  ["Korku Dünyaları","Fog Survival","fog-survival"],
  ["Korku Dünyaları","Night Dweller tarzı dünya","night-dweller-tarzi-dunya"],
  ["Korku Dünyaları","From The Fog tarzı dünya","from-the-fog-tarzi-dunya"],
  ["Korku Dünyaları","Monster Island","monster-island"],
  ["RPG Dünyaları","Fantasy RPG","fantasy-rpg"],
  ["RPG Dünyaları","Magic RPG","magic-rpg"],
  ["RPG Dünyaları","Dark Fantasy","dark-fantasy"],
  ["RPG Dünyaları","Dungeon RPG","dungeon-rpg"],
  ["RPG Dünyaları","Classes RPG","classes-rpg"],
  ["RPG Dünyaları","Level System Survival","level-system-survival"],
  ["RPG Dünyaları","Boss Progression","boss-progression"],
  ["RPG Dünyaları","Kingdom RPG","kingdom-rpg"],
  ["RPG Dünyaları","Samurai RPG","samurai-rpg"],
  ["RPG Dünyaları","Viking RPG","viking-rpg"],
  ["RPG Dünyaları","Pirate RPG","pirate-rpg"],
  ["Medeniyet ve Roleplay","Civilization Experiment","civilization-experiment"],
  ["Medeniyet ve Roleplay","100 Players Civilization","100-players-civilization"],
  ["Medeniyet ve Roleplay","Towny World","towny-world"],
  ["Medeniyet ve Roleplay","Medieval Kingdoms","medieval-kingdoms"],
  ["Medeniyet ve Roleplay","Empires","empires"],
  ["Medeniyet ve Roleplay","Tribes","tribes"],
  ["Medeniyet ve Roleplay","War of Kingdoms","war-of-kingdoms"],
  ["Medeniyet ve Roleplay","Political SMP","political-smp"],
  ["Medeniyet ve Roleplay","Economy SMP","economy-smp"],
  ["Medeniyet ve Roleplay","Origins SMP","origins-smp"],
  ["Teknoloji ve Modlu","Industrial Survival","industrial-survival"],
  ["Teknoloji ve Modlu","Automation World","automation-world"],
  ["Teknoloji ve Modlu","Factory World","factory-world"],
  ["Teknoloji ve Modlu","Create Mod World","create-mod-world"],
  ["Teknoloji ve Modlu","Space Exploration","space-exploration"],
  ["Teknoloji ve Modlu","Nuclear Technology","nuclear-technology"],
  ["Teknoloji ve Modlu","Steampunk","steampunk"],
  ["Teknoloji ve Modlu","Cyberpunk","cyberpunk"],
  ["Teknoloji ve Modlu","Modern City Survival","modern-city-survival"],
  ["Teknoloji ve Modlu","Tech vs Magic","tech-vs-magic"],
  ["Fantastik Temalar","Dragons World","dragons-world"],
  ["Fantastik Temalar","Elves vs Orcs","elves-vs-orcs"],
  ["Fantastik Temalar","Dwarven Kingdom","dwarven-kingdom"],
  ["Fantastik Temalar","Giant Monsters","giant-monsters"],
  ["Fantastik Temalar","Mythology Survival","mythology-survival"],
  ["Fantastik Temalar","Greek Mythology","greek-mythology"],
  ["Fantastik Temalar","Norse Mythology","norse-mythology"],
  ["Fantastik Temalar","Heaven vs Hell","heaven-vs-hell"],
  ["Fantastik Temalar","Demon Survival","demon-survival"],
  ["Gerçekçilik Challenge","Realistic Survival","realistic-survival"],
  ["Gerçekçilik Challenge","Seasons Survival","seasons-survival"],
  ["Gerçekçilik Challenge","Temperature Survival","temperature-survival"],
  ["Gerçekçilik Challenge","Thirst System","thirst-system"],
  ["Gerçekçilik Challenge","Limited Inventory","limited-inventory"],
  ["Gerçekçilik Challenge","Realistic Farming","realistic-farming"],
  ["Gerçekçilik Challenge","Realistic Mining","realistic-mining"],
  ["Gerçekçilik Challenge","Hardcore Weather","hardcore-weather"],
  ["Gerçekçilik Challenge","Realistic Animals","realistic-animals"],
  ["Ada ve Okyanus","Tiny Island","tiny-island"],
  ["Ada ve Okyanus","Desert Island","desert-island"],
  ["Ada ve Okyanus","Tropical Island","tropical-island"],
  ["Ada ve Okyanus","Frozen Island","frozen-island"],
  ["Ada ve Okyanus","OceanBlock","oceanblock"],
  ["Ada ve Okyanus","Underwater Survival","underwater-survival"],
  ["Ada ve Okyanus","Atlantis Survival","atlantis-survival"],
  ["Ada ve Okyanus","Pirate Islands","pirate-islands"],
  ["Yeraltı Konseptleri","Underground Only","underground-only"],
  ["Yeraltı Konseptleri","CaveBlock","caveblock"],
  ["Yeraltı Konseptleri","StoneBlock","stoneblock"],
  ["Yeraltı Konseptleri","Deep Dark Survival","deep-dark-survival"],
  ["Yeraltı Konseptleri","Mineshaft Survival","mineshaft-survival"],
  ["Yeraltı Konseptleri","Bedrock Level Survival","bedrock-level-survival"],
  ["Yeraltı Konseptleri","No Surface Challenge","no-surface-challenge"],
  ["Savaş Dünyaları","Factions","factions"],
  ["Savaş Dünyaları","Anarchy","anarchy"],
  ["Savaş Dünyaları","Lifesteal","lifesteal"],
  ["Savaş Dünyaları","KitPvP World","kitpvp-world"],
  ["Savaş Dünyaları","BedWars tarzı dünya","bedwars-tarzi-dunya"],
  ["Savaş Dünyaları","Hunger Games","hunger-games"],
  ["Savaş Dünyaları","Battle Royale","battle-royale"],
  ["Savaş Dünyaları","Capture the Flag","capture-the-flag"],
  ["Savaş Dünyaları","Castle Siege","castle-siege"],
  ["Savaş Dünyaları","Red vs Blue","red-vs-blue"],
  ["Savaş Dünyaları","Clan Wars","clan-wars"],
  ["Yaratıcı Proje Dünyaları","Mega City","mega-city"],
  ["Yaratıcı Proje Dünyaları","Medieval City","medieval-city"],
  ["Yaratıcı Proje Dünyaları","Modern City","modern-city"],
  ["Yaratıcı Proje Dünyaları","Cyberpunk City","cyberpunk-city"],
  ["Yaratıcı Proje Dünyaları","Fantasy Kingdom","fantasy-kingdom"],
  ["Yaratıcı Proje Dünyaları","Giant Castle","giant-castle"],
  ["Yaratıcı Proje Dünyaları","Theme Park","theme-park"],
  ["Yaratıcı Proje Dünyaları","Zoo","zoo"],
  ["Yaratıcı Proje Dünyaları","Airport","airport"],
  ["Yaratıcı Proje Dünyaları","Country Recreation","country-recreation"],
  ["Yaratıcı Proje Dünyaları","Earth Map","earth-map"],
  ["Yaratıcı Proje Dünyaları","Realistic Village","realistic-village"],
  ["Yaratıcı Proje Dünyaları","Mega Base World","mega-base-world"],
  ["Speedrun Konseptleri","Normal Speedrun","normal-speedrun"],
  ["Speedrun Konseptleri","Hardcore Speedrun","hardcore-speedrun"],
  ["Speedrun Konseptleri","Random Seed Speedrun","random-seed-speedrun"],
  ["Speedrun Konseptleri","Set Seed Speedrun","set-seed-speedrun"],
  ["Speedrun Konseptleri","One Chunk Speedrun","one-chunk-speedrun"],
  ["Speedrun Konseptleri","SkyBlock Speedrun","skyblock-speedrun"],
  ["Speedrun Konseptleri","Nether Only Speedrun","nether-only-speedrun"],
  ["Speedrun Konseptleri","No Armor Speedrun","no-armor-speedrun"],
  ["Arkadaşlarla Eğlencelik","Manhunt","manhunt"],
  ["Arkadaşlarla Eğlencelik","Bingo","bingo"],
  ["Arkadaşlarla Eğlencelik","Hide and Seek","hide-and-seek"],
  ["Arkadaşlarla Eğlencelik","Prop Hunt","prop-hunt"],
  ["Arkadaşlarla Eğlencelik","Build Battle","build-battle"],
  ["Arkadaşlarla Eğlencelik","Guess the Build","guess-the-build"],
  ["Arkadaşlarla Eğlencelik","Parkour Race","parkour-race"],
  ["Arkadaşlarla Eğlencelik","Maze Survival","maze-survival"],
  ["Tuhaf Challenge","Every Block Is TNT","every-block-is-tnt"],
  ["Tuhaf Challenge","Everything Is Lucky Blocks","everything-is-lucky-blocks"],
  ["Tuhaf Challenge","World Is Made of Glass","world-is-made-of-glass"],
  ["Tuhaf Challenge","World Is Made of Sand","world-is-made-of-sand"],
  ["Tuhaf Challenge","World Is Made of Lava","world-is-made-of-lava"],
  ["Tuhaf Challenge","Giant World","giant-world"],
  ["Tuhaf Challenge","Tiny World","tiny-world"],
  ["Tuhaf Challenge","Upside-Down World","upside-down-world"],
  ["Tuhaf Challenge","Invisible Blocks World","invisible-blocks-world"],
  ["Tuhaf Challenge","Gravity Challenge","gravity-challenge"],
  ["Tuhaf Challenge","Mobs Are Giant","mobs-are-giant"],
  ["Tuhaf Challenge","Mobs Are Tiny","mobs-are-tiny"],
  ["Tuhaf Challenge","Every Mob Explodes","every-mob-explodes"],
]

const NATIVE:Record<string,WorldNativeProfile> = {
  "klasik-survival":{"gamemode":"survival","difficulty":"normal","hardcore":false,"levelType":"default","generateStructures":true},
  "survival":{"gamemode":"survival","difficulty":"normal","hardcore":false,"levelType":"default","generateStructures":true},
  "hardcore-survival":{"gamemode":"survival","difficulty":"hard","hardcore":true,"levelType":"default","generateStructures":true},
  "hardcore":{"gamemode":"survival","difficulty":"hard","hardcore":true,"levelType":"default","generateStructures":true},
  "creative":{"gamemode":"creative","difficulty":"normal","hardcore":false,"levelType":"default","generateStructures":true},
  "adventure":{"gamemode":"adventure","difficulty":"normal","hardcore":false,"levelType":"default","generateStructures":true},
  "peaceful-survival":{"gamemode":"survival","difficulty":"peaceful","hardcore":false,"levelType":"default","generateStructures":true},
  "bariscil-survival":{"gamemode":"survival","difficulty":"peaceful","hardcore":false,"levelType":"default","generateStructures":true},
  "superflat-survival":{"gamemode":"survival","difficulty":"normal","hardcore":false,"levelType":"flat","generateStructures":true},
  "amplified-world":{"gamemode":"survival","difficulty":"normal","hardcore":false,"levelType":"amplified","generateStructures":true},
  "large-biomes":{"gamemode":"survival","difficulty":"normal","hardcore":false,"levelType":"largeBiomes","generateStructures":true},
}

export const WORLD_TEMPLATES:WorldTemplate[] = rows.map(([category,name,id])=>{ const profile=NATIVE[id]; return profile ? {id,name,category,mode:'native' as const,profile,description:'Minecraft sunucu ayarlarıyla doğrudan oluşturulabilir.'} : {id,name,category,mode:'package' as const,packageKey:id,description:'Bu konsept datapack/mod/harita içeriği gerektirir. Node üzerinde onaylı dünya şablon paketi bulunursa kurulabilir.'} })
export const WORLD_TEMPLATE_MAP = new Map(WORLD_TEMPLATES.map(item=>[item.id,item]))
export const WORLD_TEMPLATE_CATEGORIES = [...new Set(WORLD_TEMPLATES.map(item=>item.category))]
