import { createHash, timingSafeEqual } from 'node:crypto'
import { NextRequest, NextResponse } from 'next/server'
import { and, asc, eq } from 'drizzle-orm'
import { z } from 'zod'
import { db } from '@/lib/db'
import { agentCommands, backups, consoleLogs, lostItems, nodes, operationLogs, servers, worlds } from '@/lib/db/schema'

const hash=(v:string)=>createHash('sha256').update(v).digest('hex')
async function getNode(request:NextRequest){const id=request.headers.get('x-node-id');const token=request.headers.get('authorization')?.replace(/^Bearer\s+/i,'');if(!id||!token)return null;const node=(await db.select().from(nodes).where(eq(nodes.id,id)).limit(1))[0];if(!node)return null;const actual=Buffer.from(hash(token));const expected=Buffer.from(node.agentTokenHash);return actual.length===expected.length&&timingSafeEqual(actual,expected)?node:null}
export async function GET(request:NextRequest){const node=await getNode(request);if(!node)return NextResponse.json({error:'Unauthorized'},{status:401});const candidates=await db.select().from(agentCommands).where(and(eq(agentCommands.nodeId,node.id),eq(agentCommands.status,'queued'))).orderBy(asc(agentCommands.createdAt)).limit(1);const commands=[];for(const candidate of candidates){const claimed=await db.update(agentCommands).set({status:'processing'}).where(and(eq(agentCommands.id,candidate.id),eq(agentCommands.status,'queued'))).returning();if(claimed[0])commands.push(claimed[0])}return NextResponse.json({commands})}
const itemSchema=z.object({eventId:z.string().min(1).max(100),serverId:z.string().uuid(),playerUuid:z.string().max(40).nullable().optional(),playerName:z.string().max(40).nullable().optional(),itemId:z.string().max(150),itemName:z.string().max(200),amount:z.number().int().min(1).max(100000),reason:z.string().max(40),world:z.string().max(100),x:z.number().int(),y:z.number().int(),z:z.number().int(),metadata:z.record(z.string(),z.unknown()).default({}),occurredAt:z.coerce.date()})
export async function POST(request:NextRequest){const node=await getNode(request);if(!node)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await request.json()
if(body.type==='heartbeat')await db.update(nodes).set({status:'online',lastHeartbeat:new Date(),cpuPercent:body.cpuPercent??0,memoryUsedMb:body.memoryUsedMb??0,memoryTotalMb:body.memoryTotalMb??0,diskUsedGb:body.diskUsedGb??0,diskTotalGb:body.diskTotalGb??0,updatedAt:new Date()}).where(and(eq(nodes.id,node.id),eq(nodes.userId,node.userId)))
else if(body.type==='result'){const command=(await db.select().from(agentCommands).where(and(eq(agentCommands.id,body.commandId),eq(agentCommands.userId,node.userId))).limit(1))[0];if(command){await db.update(agentCommands).set({status:body.ok?'completed':'failed',result:body.result??{},completedAt:new Date()}).where(eq(agentCommands.id,command.id));await db.insert(operationLogs).values({userId:node.userId,serverId:command.serverId!,operation:command.type,status:body.ok?'completed':'failed',message:body.result?.error??null});if(body.ok&&command.serverId&&['backup','CREATE_BACKUP','CREATE_WORLD_BACKUP'].includes(command.type)&&body.result?.path){const world=(await db.select({id:worlds.id}).from(worlds).where(and(eq(worlds.serverId,command.serverId),eq(worlds.isActive,true))).limit(1))[0];if(world)await db.insert(backups).values({userId:node.userId,worldId:world.id,blobPathname:String(body.result.path).slice(0,500),sizeMb:Number(body.result.sizeBytes??0)/1048576,sizeBytes:Number(body.result.sizeBytes??0),createdBy:node.userId})}if(!body.ok&&command.type==='install')await db.update(servers).set({status:'failed',installError:String(body.result?.error??'Kurulum başarısız'),updatedAt:new Date()}).where(eq(servers.id,command.serverId!));if(body.ok&&command.type==='delete-server')await db.update(servers).set({status:'deleted',updatedAt:new Date()}).where(and(eq(servers.id,command.serverId!),eq(servers.userId,node.userId)))}}
else if(body.type==='progress'&&body.serverId)await db.update(servers).set({status:String(body.status??'installing'),installProgress:Math.max(0,Math.min(100,Number(body.progress)||0)),installError:null,updatedAt:new Date()}).where(and(eq(servers.id,body.serverId),eq(servers.userId,node.userId)))
else if(body.type==='log'&&body.serverId&&typeof body.line==='string')await db.insert(consoleLogs).values({userId:node.userId,serverId:body.serverId,stream:body.stream==='stderr'?'stderr':'stdout',line:body.line.slice(0,8000)})
else if(body.type==='server-status'&&body.serverId)await db.update(servers).set({status:body.status,pid:body.pid??null,playerCount:body.playerCount??0,installProgress:body.status==='ready'||body.status==='stopped'?100:undefined,updatedAt:new Date()}).where(and(eq(servers.id,body.serverId),eq(servers.userId,node.userId)))
else if(body.type==='lost-items'){const items=z.array(itemSchema).max(200).parse(body.items);for(const item of items){const server=(await db.select().from(servers).where(and(eq(servers.id,item.serverId),eq(servers.nodeId,node.id),eq(servers.itemTrackingEnabled,true))).limit(1))[0];if(server)await db.insert(lostItems).values({userId:server.userId,...item}).onConflictDoNothing()}}
return NextResponse.json({ok:true})}
