import { headers } from 'next/headers'
import { NextRequest, NextResponse } from 'next/server'
import { and, desc, eq, inArray } from 'drizzle-orm'
import { auth } from '@/lib/auth'
import { db } from '@/lib/db'
import { backups, serverPermissions, servers, worlds } from '@/lib/db/schema'

async function actor() { const session = await auth.api.getSession({ headers: await headers() }); return session?.user ?? null }
async function owned(id:string, userId:string) { const server = (await db.select().from(servers).where(and(eq(servers.id,id),eq(servers.userId,userId))).limit(1))[0]; if(server) return server; const permission=(await db.select().from(serverPermissions).where(and(eq(serverPermissions.serverId,id),eq(serverPermissions.userId,userId))).limit(1))[0]; if(!permission?.canBackup) return null; return (await db.select().from(servers).where(eq(servers.id,id)).limit(1))[0] ?? null }
export async function GET(request:NextRequest){const a=await actor();if(!a)return NextResponse.json({error:'Unauthorized'},{status:401});const serverId=request.nextUrl.searchParams.get('serverId');if(!serverId)return NextResponse.json({error:'serverId gerekli'},{status:400});const server=await owned(serverId,a.id);if(!server)return NextResponse.json({error:'Forbidden'},{status:403});const rows=await db.select({id:backups.id,worldId:backups.worldId,blobPathname:backups.blobPathname,sizeMb:backups.sizeMb,sizeBytes:backups.sizeBytes,createdAt:backups.createdAt,worldName:worlds.name}).from(backups).innerJoin(worlds,eq(backups.worldId,worlds.id)).where(and(eq(worlds.serverId,serverId),eq(backups.userId,server.userId))).orderBy(desc(backups.createdAt)).limit(100);return NextResponse.json({backups:rows},{headers:{'Cache-Control':'private, no-store'}})}
export async function POST(request:NextRequest){const a=await actor();if(!a)return NextResponse.json({error:'Unauthorized'},{status:401});const body=await request.json();const serverId=String(body.serverId||'');const server=await owned(serverId,a.id);if(!server)return NextResponse.json({error:'Forbidden'},{status:403});const type=String(body.type||'backup');const allowed=['backup','restore-backup','delete-backup'];if(!allowed.includes(type))return NextResponse.json({error:'Geçersiz backup işlemi'},{status:400});if((type==='restore-backup'||type==='delete-backup')&&body.confirm!==true)return NextResponse.json({error:'Onay gerekli'},{status:400});const [command]=await db.insert((await import('@/lib/db/schema')).agentCommands).values({userId:server.userId,nodeId:server.nodeId,serverId,type,payload:{path:body.path,label:body.label||'manual',kind:body.kind||'full',confirm:body.confirm===true},status:'queued'}).returning();return NextResponse.json({ok:true,command},{status:202})}
