'use client'

import { useEffect, useMemo, useState } from 'react'
import useSWR from 'swr'
import { useParams, useRouter } from 'next/navigation'
import {
  ArrowLeft, Clock3, Database, Download, FileText, Folder, Gamepad2, Globe2,
  HardDrive, Menu, Network, Play, RefreshCw, RotateCcw, Save, Server as ServerIcon,
  Settings2, Shield, Square, Terminal, Users, Wrench, X
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { ServerFilesManager } from '@/components/server-files-manager'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

const MAX_DIRECT_UPLOAD = 2 * 1024 * 1024 * 1024

type Server = {
  id:string; name:string; nodeId?:string; loader:string; mcVersion:string; loaderVersion?:string|null;
  status:string; port:number; memoryMb:number; playerCount:number; installProgress:number;
  installError?:string|null; worldName?:string; publicHost?:string; connectionAddress?:string
}
type NodeInfo = { id:string; name:string; status:string; lastHeartbeat:string|null; cpuPercent:number; memoryUsedMb:number; memoryTotalMb:number; diskUsedGb:number; diskTotalGb:number }
type LogRow = { id:number; serverId:string; line:string; createdAt:string }
type WorldRow = { id:string; serverId:string; name:string; isActive:boolean; sizeMb:number; seed?:string|null; lastBackupAt?:string|null }
type Permission = { userId:string; serverId:string; canStart:boolean; canStop:boolean; canRestart:boolean; canConsole:boolean; canFiles:boolean; canBackup:boolean; canReset:boolean; canViewLostItems:boolean; canManageLostItems:boolean; sections?:string[] }
type Member = { id:string; name:string; email:string; role:string; approved:boolean }
type Operation = { id:number; serverId:string; operation:string; status:string; message?:string|null; createdAt:string }
type Panel = { servers:Server[]; nodes:NodeInfo[]; logs:LogRow[]; worlds:WorldRow[]; users:Member[]; permissions:Permission[]; currentPermission?:Permission|null; allowedSections?:string[]; operations:Operation[]; actor?:{id:string;name:string;email:string;role:string} }
type BackupRow = { id:string; worldId:string; worldName:string; blobPathname:string; sizeMb:number; createdAt:string; status?:'queued'|'running'|'completed'|'failed'; progress?:number }

async function readJson(response:Response){
  const text = await response.text()
  try { return text ? JSON.parse(text) : {} }
  catch { throw new Error(response.ok ? 'Sunucudan geçersiz yanıt alındı' : `Sunucu hatası (${response.status}): ${text.slice(0,180)}`) }
}
const fetcher=(url:string)=>fetch(url,{cache:'no-store',headers:{accept:'application/json'}}).then(async r=>{const d=await readJson(r);if(!r.ok)throw new Error(d.error??'İstek başarısız');return d})

async function directUploadFile(serverId:string,file:File,category:string,onProgress?:(percent:number)=>void){
  const started=await fetch('/api/direct-upload',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'start',serverId,filename:file.name,size:file.size,category})})
  const s=await readJson(started) as {error?:string;uploadId?:string;commandId?:string;chunkSize?:number}
  if(!started.ok||!s.uploadId||!s.commandId||!s.chunkSize) throw new Error(s.error??`Yükleme başlatılamadı (${started.status})`)
  const total=Math.ceil(file.size/s.chunkSize)
  for(let part=0;part<total;part++){
    const chunk=file.slice(part*s.chunkSize,Math.min(file.size,(part+1)*s.chunkSize)); let last=''
    for(let attempt=0;attempt<3;attempt++){
      try{
        const r=await fetch(`/api/direct-upload?commandId=${encodeURIComponent(s.commandId)}&uploadId=${encodeURIComponent(s.uploadId)}&part=${part}`,{method:'PUT',headers:{'content-type':'application/octet-stream'},body:chunk})
        const d=await readJson(r); if(!r.ok)throw new Error(d.error??`Parça ${part+1} yüklenemedi`); last=''; break
      }catch(error){last=error instanceof Error?error.message:'Parça yüklenemedi';if(attempt<2)await new Promise(resolve=>setTimeout(resolve,750*(attempt+1)))}
    }
    if(last)throw new Error(last); onProgress?.(Math.round((part+1)/total*100))
  }
  const done=await fetch('/api/direct-upload',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'complete',commandId:s.commandId,uploadId:s.uploadId})})
  const result=await readJson(done); if(!done.ok)throw new Error(result.error??'Yükleme tamamlanamadı'); return result
}

const nav=[
  ['overview','Genel Bakış',Gamepad2],['settings','Ayarlar',Settings2],['console','Konsol',Terminal],['logs','Günlük',FileText],
  ['players','Oyuncular',Users],['software','Yazılım',Wrench],['files','Dosyalar',Folder],['worlds','Dünyalar',Globe2],
  ['backups','Yedekler',RotateCcw],['network','Ağ / Portlar',Network],['schedules','Zamanlamalar',Clock3],['databases','Veritabanları',Database],['access','Erişim',Shield]
] as const

export default function ServerPage(){
  const {id}=useParams<{id:string}>(); const router=useRouter()
  const {data,error,mutate}=useSWR<Panel>(`/api/panel?serverId=${id}`,fetcher,{refreshInterval:3000})
  const server=data?.servers.find(s=>s.id===id); const node=data?.nodes?.[0]
  const manager=data?.actor?.role==='manager'; const permission=data?.currentPermission??undefined
  const allowedSections=useMemo(()=>data?.allowedSections?.length?data.allowedSections:(manager?nav.map(([key])=>key):['overview','logs']),[data?.allowedSections,manager])
  const visibleNav=useMemo(()=>nav.filter(([key])=>allowedSections.includes(key)),[allowedSections])
  const {data:backupData,error:backupError,mutate:mutateBackups}=useSWR<{backups:BackupRow[]}>(allowedSections.includes('backups')?`/api/backups?serverId=${id}`:null,fetcher,{refreshInterval:5000})
  const [section,setSection]=useState<(typeof nav)[number][0]>('overview'); const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState('')
  const [motd,setMotd]=useState('BlockCtrl sunucusu'); const [maxPlayers,setMaxPlayers]=useState('20'); const [onlineMode,setOnlineMode]=useState(false); const [gamemode,setGamemode]=useState('survival'); const [difficulty,setDifficulty]=useState('easy'); const [pvp,setPvp]=useState(true); const [viewDistance,setViewDistance]=useState('10'); const [simulationDistance,setSimulationDistance]=useState('10'); const [spawnProtection,setSpawnProtection]=useState('16'); const [allowFlight,setAllowFlight]=useState(false); const [whitelist,setWhitelist]=useState(false)
  const [playerName,setPlayerName]=useState(''); const [newPort,setNewPort]=useState(''); const [worldName,setWorldName]=useState('world_2'); const [softwareLoader,setSoftwareLoader]=useState('paper'); const [softwareVersion,setSoftwareVersion]=useState('1.21.1'); const [softwareLoaderVersion,setSoftwareLoaderVersion]=useState(''); const [consoleLine,setConsoleLine]=useState('')
  const logs=useMemo(()=>data?.logs?.filter(l=>l.serverId===id).slice(-150)??[],[data,id])
  const playerNames=useMemo(()=>{for(const row of [...logs].reverse()){const m=row.line.match(/There are \d+ of a max of \d+ players online:?\s*(.*)$/i);if(m){return m[1].split(',').map(x=>x.trim()).filter(Boolean)}}return []},[logs])
  const canStart=!!manager||!!permission?.canStart; const canStop=!!manager||!!permission?.canStop; const canRestart=!!manager||!!permission?.canRestart; const canConsole=!!manager||!!permission?.canConsole; const canFiles=!!manager||!!permission?.canFiles; const canBackup=!!manager||!!permission?.canBackup; const canReset=!!manager||!!permission?.canReset
  useEffect(()=>{if(visibleNav.length&&!visibleNav.some(([key])=>key===section))setSection(visibleNav[0][0])},[visibleNav,section])

  async function command(type:string,payload:Record<string,unknown>={},destructive=false){
    if(!server)return; let confirmName: string|undefined
    if(destructive){confirmName=prompt(`Onaylamak için “${server.name}” yazın.`)??undefined;if(confirmName!==server.name)return}
    setBusy(true);setNotice('')
    try{const r=await fetch('/api/panel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'command',serverId:id,type,payload:{...payload,confirm:destructive?true:payload.confirm},confirm:confirmName})});const d=await readJson(r);if(!r.ok)throw new Error(d.error??'İşlem başarısız');setNotice('İşlem kuyruğa alındı.');await mutate()}
    catch(e){setNotice(e instanceof Error?e.message:'İşlem başarısız')} finally{setBusy(false)}
  }
  async function backupAction(type:string,payload:Record<string,unknown>={},requiresConfirm=false){
    if(requiresConfirm&&prompt('Bu işlem için CONFIRM yazın.')!=='CONFIRM')return;setBusy(true);setNotice('')
    try{const r=await fetch('/api/backups',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({serverId:id,type,payload,...payload,confirm:requiresConfirm})});const d=await readJson(r);if(!r.ok)throw new Error(d.error??'Yedek işlemi başarısız');setNotice('Yedek işlemi kuyruğa alındı.');await mutateBackups();await mutate()}
    catch(e){setNotice(e instanceof Error?e.message:'Yedek işlemi başarısız')}finally{setBusy(false)}
  }
  async function permissionAction(userId:string,grant:boolean){setBusy(true);setNotice('');try{const r=await fetch('/api/panel',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(grant?{action:'set-permission',serverId:id,userId,canStart:true,canStop:true,canRestart:true,canConsole:true,canFiles:true,canBackup:true,canReset:true,canViewLostItems:true,canManageLostItems:true}:{action:'remove-permission',serverId:id,userId})});const d=await readJson(r);if(!r.ok)throw new Error(d.error??'Erişim güncellenemedi');setNotice(grant?'Kullanıcıya tam erişim verildi.':'Kullanıcının erişimi kaldırıldı.');await mutate()}catch(e){setNotice(e instanceof Error?e.message:'Erişim güncellenemedi')}finally{setBusy(false)}}
  const saveSettings=()=>command('set-properties',{'max-players':Math.max(1,Math.min(500,Number(maxPlayers)||20)),motd:motd.slice(0,150),'online-mode':onlineMode,gamemode,difficulty,pvp,'view-distance':Math.max(2,Math.min(32,Number(viewDistance)||10)),'simulation-distance':Math.max(2,Math.min(32,Number(simulationDistance)||10)),'spawn-protection':Math.max(0,Math.min(256,Number(spawnProtection)||16)),'allow-flight':allowFlight,'white-list':whitelist})
  async function upload(e:React.ChangeEvent<HTMLInputElement>,category:string){const file=e.target.files?.[0];if(!file)return;if(file.size>MAX_DIRECT_UPLOAD){setNotice('Dosya 2 GB sınırını aşamaz.');e.target.value='';return}setBusy(true);try{await directUploadFile(id,file,category,p=>setNotice(`${file.name} yükleniyor: %${p}`));setNotice(`${file.name} sunucuya yüklendi.`);await mutate()}catch(err){setNotice(err instanceof Error?err.message:'Dosya yüklenemedi')}finally{setBusy(false);e.target.value=''}}
  function downloadLogs(){const body=logs.map(l=>`[${new Date(l.createdAt).toLocaleString('tr-TR')}] ${l.line}`).join('\n');const url=URL.createObjectURL(new Blob([body],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`${server?.name??'server'}-latest.log`;a.click();URL.revokeObjectURL(url)}

  if(error)return <main className="p-8 text-red-300">{error.message}</main>; if(!server)return <main className="p-8">Sunucu bulunamadı.</main>
  const running=server.status==='running'; const diskPct=node?.diskTotalGb?Math.round(node.diskUsedGb/node.diskTotalGb*100):0; const ramPct=node?.memoryTotalMb?Math.round(node.memoryUsedMb/node.memoryTotalMb*100):0

  return <main className="min-h-svh bg-[#08110e] text-slate-100"><div className="flex min-h-svh">
    <aside className={`${open?'translate-x-0':'-translate-x-full'} fixed inset-y-0 z-30 w-64 border-r border-emerald-950/80 bg-[#0f2019] p-3 transition-transform lg:static lg:translate-x-0`}>
      <div className="mb-5 flex items-center justify-between px-2 py-2"><div><p className="text-xs uppercase tracking-[.22em] text-emerald-400">BlockCtrl</p><h1 className="mt-1 text-lg font-bold">{server.name}</h1></div><Button size="icon" variant="ghost" className="lg:hidden" onClick={()=>setOpen(false)}><X/></Button></div>
      <nav className="flex flex-col gap-1">{visibleNav.map(([key,label,Icon])=><button key={key} onClick={()=>{setSection(key);setOpen(false)}} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-left text-sm font-medium transition ${section===key?'bg-emerald-500 text-emerald-950':'text-slate-200 hover:bg-emerald-950/50'}`}><Icon className="size-4"/>{label}</button>)}</nav>
      <Button variant="ghost" className="mt-5 w-full justify-start text-slate-300" onClick={()=>router.push('/')}><ArrowLeft className="mr-2 size-4"/>Sunuculara dön</Button>
    </aside>
    <section className="min-w-0 flex-1">
      <header className="sticky top-0 z-20 flex items-center justify-between border-b border-slate-800 bg-[#0b1713]/95 px-4 py-3 backdrop-blur lg:px-6"><Button size="icon" variant="ghost" className="lg:hidden" onClick={()=>setOpen(true)}><Menu/></Button><div><p className="text-xs text-slate-500">Sunucu yönetimi / {nav.find(n=>n[0]===section)?.[1]}</p><h2 className="text-lg font-semibold">{server.name}</h2></div><div className="hidden flex-wrap gap-2 sm:flex">{canStart&&<Button size="sm" onClick={()=>command('start')} disabled={busy||running}><Play className="mr-1 size-4"/>Başlat</Button>}{canStop&&<Button size="sm" variant="outline" onClick={()=>command('stop')} disabled={busy||!running}><Square className="mr-1 size-4"/>Durdur</Button>}{canRestart&&<Button size="sm" variant="outline" onClick={()=>command('restart')} disabled={busy||!running}><RefreshCw className="mr-1 size-4"/>Restart</Button>}</div></header>
      <div className="space-y-5 p-4 lg:p-6">{notice&&<div role="status" className="rounded-lg border border-emerald-500/25 bg-emerald-950/30 p-3 text-sm text-emerald-200">{notice}</div>}

      {section==='overview'&&<><SectionTitle title="Genel Bakış" text="Sunucu durumu, sistem kaynakları ve hızlı erişim."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric title="Durum" value={running?'Çevrimiçi':'Kapalı'} sub={`${server.loader} ${server.mcVersion}`}/><Metric title="Oyuncular" value={`${server.playerCount} / ${maxPlayers}`} sub="Anlık oyuncu sayısı"/><Metric title="CPU" value={node?`%${Math.round(node.cpuPercent)}`:'—'} sub={node?.name??'Node bilgisi bekleniyor'}/><Metric title="RAM" value={node?`${(node.memoryUsedMb/1024).toFixed(1)} / ${(node.memoryTotalMb/1024).toFixed(1)} GB`:`${server.memoryMb} MB`} sub={node?`%${ramPct} kullanım`:'Sunucu limiti'}/><Metric title="Disk" value={node?.diskTotalGb?`${node.diskUsedGb.toFixed(1)} / ${node.diskTotalGb.toFixed(1)} GB`:'—'} sub={node?.diskTotalGb?`%${diskPct} kullanım`:'Agent disk metriği bekleniyor'}/><Metric title="IP / Adres" value={server.connectionAddress??`${server.publicHost??'IP bekleniyor'}:${server.port}`} sub="Oyuncuların bağlanacağı adres"/></div><CardBox title="Hızlı işlemler" text="En sık kullanılan sunucu işlemleri"><div className="flex flex-wrap gap-2">{canStart&&<Button onClick={()=>command('start')} disabled={busy||running}>Başlat</Button>}{canStop&&<Button variant="outline" onClick={()=>command('stop')} disabled={busy||!running}>Durdur</Button>}{allowedSections.includes('console')&&<Button variant="outline" onClick={()=>setSection('console')}>Konsola git</Button>}{allowedSections.includes('files')&&<Button variant="outline" onClick={()=>setSection('files')}>Dosyalara git</Button>}{canBackup&&<Button variant="outline" onClick={()=>backupAction('backup',{kind:'full',label:'manual'})}>Yedek al</Button>}</div></CardBox><CardBox title="Son işlemler" text="Agent tarafından tamamlanan son görevler"><OperationList rows={(data?.operations??[]).slice(0,8)}/></CardBox></>}

      {section==='settings'&&<><SectionTitle title="Ayarlar" text="server.properties değerlerini panelden yönetin."/><CardBox title="Genel" text="Değişiklikleri kaydetmek için sunucunun kapalı olması gerekir"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="MOTD" value={motd} set={setMotd}/><Field label="Maksimum oyuncu" value={maxPlayers} set={setMaxPlayers}/><Field label="Oyun modu" value={gamemode} set={setGamemode}/><Field label="Zorluk" value={difficulty} set={setDifficulty}/><Field label="Görüş mesafesi" value={viewDistance} set={setViewDistance}/><Field label="Simülasyon mesafesi" value={simulationDistance} set={setSimulationDistance}/><Field label="Spawn koruması" value={spawnProtection} set={setSpawnProtection}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Toggle label="PvP" checked={pvp} set={setPvp}/><Toggle label="Premium doğrulama" checked={onlineMode} set={setOnlineMode}/><Toggle label="Whitelist" checked={whitelist} set={setWhitelist}/><Toggle label="Uçuşa izin ver" checked={allowFlight} set={setAllowFlight}/></div>{!onlineMode&&<div className="mt-4 rounded-md border border-amber-500/30 bg-amber-950/25 p-3 text-sm text-amber-200">Offline/cracked giriş açık. Kullanıcı adı taklidi mümkün olduğundan whitelist veya ek kimlik doğrulama kullanın.</div>}{canReset?<Button className="mt-4" onClick={saveSettings} disabled={busy||running}><Save className="mr-2 size-4"/>Ayarları kaydet</Button>:<p className="mt-4 text-sm text-slate-500">Bu sayfa salt okunur. Ayar değiştirme izniniz yok.</p>}</CardBox></>}

      {section==='console'&&<><SectionTitle title="Konsol" text="Canlı sunucu çıktısını izleyin ve komut gönderin."/><CardBox title="Canlı konsol" text={running?'Sunucu çalışıyor':'Sunucu kapalı'}><div className="h-[430px] overflow-auto rounded-md border border-slate-800 bg-black/60 p-4 font-mono text-xs leading-5">{logs.length?logs.map(l=><div key={l.id} className={/WARN|ERROR|Exception/i.test(l.line)?'text-amber-300':'text-slate-300'}><span className="text-slate-600">[{new Date(l.createdAt).toLocaleTimeString('tr-TR')}]</span> {l.line}</div>):<span className="text-slate-500">Henüz konsol çıktısı yok.</span>}</div><form className="mt-3 flex gap-2" onSubmit={e=>{e.preventDefault();if(consoleLine.trim()){void command('console',{line:consoleLine.trim()});setConsoleLine('')}}}><Input value={consoleLine} onChange={e=>setConsoleLine(e.target.value)} placeholder={canConsole?'say Merhaba':'Salt okunur konsol'} disabled={!running||!canConsole}/>{canConsole&&<Button disabled={!running||!consoleLine.trim()}>Gönder</Button>}</form></CardBox></>}

      {section==='logs'&&<><SectionTitle title="Günlük" text="Sunucu loglarını görüntüleyin ve indirin."/><CardBox title="latest.log görünümü" text={`${logs.length} kayıt gösteriliyor`}><div className="mb-3 flex gap-2"><Button size="sm" variant="outline" onClick={()=>mutate()}><RefreshCw className="mr-2 size-4"/>Yenile</Button><Button size="sm" variant="outline" onClick={downloadLogs}><Download className="mr-2 size-4"/>İndir</Button></div><div className="max-h-[520px] overflow-auto rounded-md bg-black/50 p-4 font-mono text-xs">{logs.map(l=><div key={l.id}>{l.line}</div>)}</div></CardBox></>}

      {section==='players'&&<><SectionTitle title="Oyuncular" text="Oyuncuları görüntüleyin ve Minecraft komutlarıyla yönetin."/><CardBox title={`Oyuncular (${server.playerCount})`} text="Liste verisi Minecraft 'list' komutunun çıktısından okunur"><div className="mb-3 flex gap-2">{canConsole&&<><Button size="sm" onClick={()=>command('list-players')} disabled={!running}>Yenile</Button><Input className="max-w-xs" placeholder="Oyuncu adı" value={playerName} onChange={e=>setPlayerName(e.target.value)}/></>}</div><div className="overflow-x-auto rounded-md border border-slate-800"><table className="w-full text-sm"><thead className="bg-slate-900/70 text-left text-slate-400"><tr><th className="p-3">Oyuncu</th><th className="p-3">Durum</th><th className="p-3">İşlemler</th></tr></thead><tbody>{playerNames.length?playerNames.map(name=><tr key={name} className="border-t border-slate-800"><td className="p-3 font-medium">{name}</td><td className="p-3 text-emerald-300">Çevrimiçi</td><td className="p-3">{canConsole?<div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>command('console',{line:`kick ${name}`})}>Kick</Button><Button size="sm" variant="outline" onClick={()=>command('console',{line:`op ${name}`})}>OP</Button><Button size="sm" variant="destructive" onClick={()=>command('console',{line:`ban ${name}`})}>Ban</Button></div>:<span className="text-xs text-slate-500">Salt okunur</span>}</td></tr>):<tr><td colSpan={3} className="p-6 text-center text-slate-500">İsim listesi henüz alınmadı. Sunucu çalışırken Yenile'ye basın.</td></tr>}</tbody></table></div>{canConsole&&playerName.trim()&&<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>command('console',{line:`whitelist add ${playerName.trim()}`})}>Whitelist ekle</Button><Button size="sm" variant="outline" onClick={()=>command('console',{line:`deop ${playerName.trim()}`})}>OP kaldır</Button></div>}</CardBox></>}

      {section==='software'&&<><SectionTitle title="Yazılım" text="Minecraft sunucu yazılımını değiştirin veya yeniden kurun."/><CardBox title="Sunucu yazılımı" text={`Mevcut: ${server.loader} ${server.mcVersion}`}><div className="grid gap-4 md:grid-cols-3"><Field label="Loader" value={softwareLoader} set={setSoftwareLoader}/><Field label="Minecraft sürümü" value={softwareVersion} set={setSoftwareVersion}/><Field label="Loader sürümü" value={softwareLoaderVersion} set={setSoftwareLoaderVersion}/></div><div className="mt-4 rounded-md border border-amber-500/30 bg-amber-950/20 p-3 text-sm text-amber-200">Yazılım değişimi mevcut sunucuyu yedekler ve yeniden kurar. Sunucu kapalı olmalıdır.</div><Button className="mt-4" disabled={!canReset||busy||running||!softwareLoader.trim()||!softwareVersion.trim()} onClick={()=>command('change-software',{loader:softwareLoader.trim().toLowerCase(),mcVersion:softwareVersion.trim(),loaderVersion:softwareLoaderVersion.trim()||undefined},true)}>Yazılımı değiştir</Button></CardBox></>}

      {section==='files'&&<><SectionTitle title="Dosyalar" text="Sunucu dosyalarını yükleyin, yönetin ve silin."/>{canFiles?<ServerFilesManager serverId={id} disabled={running}/>:<CardBox title="Salt okunur" text="Dosya içeriği güvenlik nedeniyle işlem izni olmayan kullanıcılara açılmaz."><p className="text-sm text-slate-400">Yöneticiden “Dosya ve mod işlemleri” izni isteyin.</p></CardBox>}</>}

      {section==='worlds'&&<><SectionTitle title="Dünyalar" text="Dünya klasörlerini yönetin, yükleyin ve yedekleyin."/><CardBox title="Dünyalar" text={`Aktif dünya: ${server.worldName??'world'}`}><div className="overflow-x-auto rounded-md border border-slate-800"><table className="w-full text-sm"><thead className="bg-slate-900/70 text-left text-slate-400"><tr><th className="p-3">Ad</th><th className="p-3">Durum</th><th className="p-3">Boyut</th><th className="p-3">İşlem</th></tr></thead><tbody>{(data?.worlds??[]).length?(data?.worlds??[]).map(w=><tr key={w.id} className="border-t border-slate-800"><td className="p-3">{w.name}</td><td className="p-3">{w.isActive?<span className="text-emerald-300">Aktif</span>:'Pasif'}</td><td className="p-3">{w.sizeMb?`${w.sizeMb.toFixed(1)} MB`:'—'}</td><td className="p-3">{canReset&&<Button size="sm" variant="outline" disabled={running||w.isActive} onClick={()=>command('CHANGE_WORLD',{worldName:w.name},true)}>Aktif yap</Button>}</td></tr>):<tr><td colSpan={4} className="p-6 text-center text-slate-500">Dünya kaydı bulunamadı.</td></tr>}</tbody></table></div><div className="mt-4 flex flex-wrap gap-2">{(canFiles||canReset)&&<label className="inline-flex cursor-pointer items-center rounded-md border border-slate-700 px-3 py-2 text-sm hover:bg-slate-800"><input type="file" accept=".zip" className="sr-only" onChange={e=>upload(e,'worlds')} disabled={running||busy}/>Dünya ZIP yükle</label>}{canBackup&&<Button variant="outline" onClick={()=>backupAction('backup',{kind:'world',label:'world'})}>Dünya yedeği</Button>}</div><div className="mt-4 flex max-w-xl gap-2"><Input value={worldName} onChange={e=>setWorldName(e.target.value)} placeholder="Yeni dünya adı"/>{canReset&&<Button variant="outline" disabled={running||!worldName.trim()} onClick={()=>command('create-world',{worldName:worldName.trim()},true)}>Oluştur</Button>}</div></CardBox></>}

      {section==='backups'&&<><SectionTitle title="Yedekler" text="Manuel yedek oluşturun, indirin ve geri yükleyin."/><CardBox title="Yedekler" text="Tam, dünya, config ve mod/plugin yedekleri"><div className="mb-4 flex flex-wrap gap-2">{canBackup&&<><Button onClick={()=>backupAction('backup',{kind:'full',label:'manual'})}>Yedek oluştur</Button><Button variant="outline" onClick={()=>backupAction('backup',{kind:'world',label:'world'})}>Dünya</Button><Button variant="outline" onClick={()=>backupAction('backup',{kind:'config',label:'config'})}>Config</Button><Button variant="outline" onClick={()=>backupAction('backup',{kind:'addons',label:'addons'})}>Mod/Plugin</Button></>}<Button variant="ghost" onClick={()=>mutateBackups()}>Yenile</Button></div>{backupError?<p className="text-red-300">{backupError.message}</p>:<div className="grid gap-3">{backupData?.backups?.length?backupData.backups.map(b=><div key={b.id} className="flex flex-col gap-3 rounded-lg border border-slate-800 bg-black/20 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{b.blobPathname.split('/').pop()}</p><p className="text-xs text-slate-500">{new Date(b.createdAt).toLocaleString('tr-TR')} · {b.sizeMb?`${b.sizeMb.toFixed(1)} MB`:'Boyut bekleniyor'}</p></div>{canBackup?<div className="flex gap-2"><a href={`/api/backups/${b.id}/download`} className="inline-flex items-center rounded-md border border-slate-700 px-3 py-2 text-xs">İndir</a><Button size="sm" variant="outline" onClick={()=>backupAction('restore-backup',{path:b.blobPathname},true)}>Geri yükle</Button><Button size="sm" variant="destructive" onClick={()=>backupAction('delete-backup',{path:b.blobPathname},true)}>Sil</Button></div>:<span className="text-xs text-slate-500">Salt okunur</span>}</div>):<p className="rounded-md border border-dashed border-slate-800 p-6 text-center text-slate-500">Henüz yedek yok.</p>}</div>}</CardBox></>}

      {section==='network'&&<><SectionTitle title="Ağ / Portlar" text="Minecraft portu ve node bağlantı durumunu görüntüleyin."/><div className="grid gap-4 lg:grid-cols-2"><CardBox title="Minecraft bağlantısı" text="Oyuncuların kullanacağı IP ve port"><div className="text-2xl font-semibold text-emerald-300 break-all">{server.connectionAddress??`${server.publicHost??'IP bekleniyor'}:${server.port}`}</div><div className="mt-2 text-sm text-slate-400">IP: <span className="text-slate-200">{server.publicHost??'—'}</span> · Port: <span className="text-slate-200">{server.port}</span></div><Button className="mt-3" size="sm" variant="outline" onClick={()=>navigator.clipboard.writeText(server.connectionAddress??`${server.publicHost??''}:${server.port}`)}>Adresi kopyala</Button><div className="mt-4 flex gap-2"><Input inputMode="numeric" value={newPort} onChange={e=>setNewPort(e.target.value)} placeholder="Yeni port"/>{canReset&&<Button variant="outline" disabled={running||!newPort} onClick={()=>command('change-port',{port:Number(newPort)})}>Kaydet</Button>}</div></CardBox><CardBox title="Node" text="Agent bağlantısı ve sistem bilgisi"><div className="space-y-2 text-sm"><Info label="Durum" value={node?.status??'Bilinmiyor'}/><Info label="Node" value={node?.name??'—'}/><Info label="Son sinyal" value={node?.lastHeartbeat?new Date(node.lastHeartbeat).toLocaleString('tr-TR'):'—'}/><Info label="CPU" value={node?`%${Math.round(node.cpuPercent)}`:'—'}/><Info label="RAM" value={node?`${node.memoryUsedMb} / ${node.memoryTotalMb} MB`:'—'}/></div></CardBox></div><div className="rounded-md border border-amber-500/30 bg-amber-950/20 p-3 text-sm text-amber-200">Portu panelden değiştirmek yalnızca Minecraft ayarını günceller. Oracle Cloud Security List / firewall kuralını da aynı porta açmanız gerekir.</div></>}

      {section==='schedules'&&<><SectionTitle title="Zamanlamalar" text="Otomatik görevler için yönetim alanı."/><CardBox title="Zamanlayıcı servisi" text="Bu özellik için kalıcı scheduler backend'i gerekiyor"><div className="space-y-3"><div className="rounded-md border border-slate-800 p-3"><b>Planlanan görev türleri:</b><p className="mt-1 text-sm text-slate-400">Otomatik restart, periyodik yedek, log temizleme ve bakım görevleri.</p></div><div className="rounded-md border border-amber-500/30 bg-amber-950/20 p-3 text-sm text-amber-200">Şu anda backend scheduler bağlı olmadığı için sahte “kaydedildi” mesajı göstermiyoruz. Bir sonraki backend aşamasında gerçek cron kayıtları eklenebilir.</div></div></CardBox></>}

      {section==='databases'&&<><SectionTitle title="Veritabanları" text="Minecraft eklentileri için veritabanı bağlantılarını yönetin."/><CardBox title="MySQL / MariaDB" text="Node üzerinde veritabanı servisi algılanmadı"><div className="rounded-md border border-amber-500/30 bg-amber-950/20 p-4 text-sm text-amber-200">Bu ekran tasarım olarak hazır; gerçek veritabanı oluşturma/silme için agent tarafına MariaDB/MySQL yönetim modülü eklenmesi gerekiyor. Şifreler tarayıcıya veya loglara yazılmamalı.</div></CardBox></>}

      {manager&&section==='access'&&<><SectionTitle title="Erişim" text="Bu sunucuya kimlerin ve hangi sayfaların erişebileceğini yönetin."/><CardBox title="Merkezi yetki yönetimi" text="Sunucu atama ve ayrıntılı izinler ana panelde yönetilir."><p className="text-sm text-slate-400">Sunuculara erişim artık kullanıcı kartlarında “Sunucu ekle” ile verilir. Böylece yalnız seçtiğiniz sunucular görünür ve Genel Bakış, Günlük, Konsol, Dosyalar gibi bölümler ayrı ayrı seçilebilir.</p><Button className="mt-4" variant="outline" onClick={()=>router.push('/')}>Ana panelde Kullanıcılar bölümüne git</Button></CardBox></>}
      </div>
    </section>
  </div></main>
}

function SectionTitle({title,text}:{title:string;text:string}){return <div><h3 className="text-2xl font-bold tracking-tight">{title}</h3><p className="mt-1 text-sm text-slate-400">{text}</p></div>}
function CardBox({title,text,children}:{title:string;text:string;children?:React.ReactNode}){return <Card className="border-slate-800 bg-[#101d18] text-slate-100"><CardHeader><CardTitle>{title}</CardTitle><CardDescription className="text-slate-400">{text}</CardDescription></CardHeader>{children&&<CardContent>{children}</CardContent>}</Card>}
function Metric({title,value,sub}:{title:string;value:string;sub:string}){return <Card className="border-slate-800 bg-[#101d18] text-slate-100"><CardHeader className="pb-2"><CardDescription className="text-slate-500">{title}</CardDescription><CardTitle className="text-2xl">{value}</CardTitle></CardHeader><CardContent className="text-xs text-slate-500">{sub}</CardContent></Card>}
function Field({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <div className="space-y-2"><Label>{label}</Label><Input value={value} onChange={e=>set(e.target.value)} className="border-slate-700 bg-[#0b1713]"/></div>}
function Toggle({label,checked,set}:{label:string;checked:boolean;set:(v:boolean)=>void}){return <label className="flex items-center justify-between gap-3 rounded-md border border-slate-800 bg-black/15 p-3 text-sm"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)} className="size-4 accent-emerald-500"/></label>}
function Info({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4 border-b border-slate-800 pb-2"><span className="text-slate-500">{label}</span><span className="font-medium">{value}</span></div>}
function OperationList({rows}:{rows:Operation[]}){return <div className="space-y-2">{rows.length?rows.map(o=><div key={o.id} className="flex flex-wrap items-center gap-3 rounded-md border border-slate-800 p-3 text-sm"><span className={`rounded-full px-2 py-1 text-xs ${o.status==='completed'?'bg-emerald-500/15 text-emerald-300':o.status==='failed'?'bg-red-500/15 text-red-300':'bg-amber-500/15 text-amber-300'}`}>{o.status}</span><code>{o.operation}</code><span className="ml-auto text-xs text-slate-500">{new Date(o.createdAt).toLocaleString('tr-TR')}</span>{o.message&&<p className="w-full text-red-300">{o.message}</p>}</div>):<p className="text-sm text-slate-500">Henüz işlem kaydı yok.</p>}</div>}
